In [1]:
import os
import torch

In [12]:
os.getcwd()

'd:\\Projects\\NovelGPT'

In [28]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [16]:
import json
a = 0
with open('webnovel_0.jsonl', 'r', encoding="utf-8") as f:
    for line in f:
        data = json.loads(line)
        print(data)
        a += 1
        if a == 10:
            break

{'title': '(种田文系列)无尽相思风', 'chapter': '第一章', 'text': '“水……”我站在无尽沙漠中，被大漠上骄阳燃烧起的飘渺烟波滚滚的蒸腾着，犹如烈火焚身。嘴里再也没有一丝湿润，我奔跑起来，只有一个念头，我要找到水源，我想要活……好好的活。\n感觉有人在不停的和我说话，我想回应想寻找，但却象死亡光临的那时一样无能为力。\n“水……”可能是听到我的呼救声，终于有水顺利润湿了我干涩的嘴唇，滑进喉咙……让我已被烈火烧透的身体得到了救恕。\n“思儿……娘的心肝宝贝，快点好起来好吗！”\n“娘亲愿意从此吃斋念佛，长跪佛前……”\n“老爷啊……呜……，如果我们的思儿醒不过来，我也就不活了！”\n“说的什么傻话，思儿也不会想听你这些话的，再说我们还有相知和相忆两个孩子。他们也离不开你的……”男人哽咽的再也说不下去。\n是谁在说话？好象妈妈的声音总在我耳边不停的说着话，小时候生病了，妈妈总是在耳边轻声的呢喃，就怕我小小的人儿会感觉孤单，会害怕。想起自己去世的时候母亲的放声大哭、父亲颤抖的背影，我的眼泪止不住的泛滥，泪缓缓落下延缓了我心中难忍的疼痛。妈妈，女儿下辈子还做您的女儿，一个健康阳光的女儿。这辈子您已经为了您病弱的女儿承受了太多。难以忘记母亲温暖的怀抱、父亲宽厚的脊背，爱别离，怨长久，求不得，放不下。\n“老爷……快来看，思儿哭了，快看啊！”\n“思儿……我的思儿，快快醒来！”一阵急促的脚步声传来，直在我耳边停下，一只轻颤的手轻拂我眼角的泪。\n我想睁开眼睛看看眼前的人，为什么声音会那么悲伤？努力再努力，微弱的光线透照裁剪出两个模糊的影子。\n“你们……别哭……”开口传来的声音，不是我前世婉转温柔的声音，是一个孩童微有嘶哑却稚嫩的声音，我愣住了。\n“佛祖保佑，佛祖保佑啊……我儿终于醒了”我隐约看到一个满脸慈爱的女人在双手合十对天膜拜，一个满脸激动的男人对着我笑。想再看多些却是极其困乏，算了睡醒了再安慰他们吧。\n一觉醒来想坐起来，却有点力不从心，苦笑下自己这病身子怎么就这么不争气呢？\n眼角瞥见一个人以手为枕趴在床边，整齐的浏海挡住了模样，只漏出一个小巧的鼻子。可能是我的移动吵醒了她，她猛然抬起头来看到半躺半坐的我，一下子叫起来\n—————————————————清醒线———————————————————\n“小姐……您醒了？太好了太好

In [17]:
# 用于存储所有组合后的文本
combined_texts = []

with open('webnovel_0.jsonl', 'r', encoding="utf-8") as f:
    for line in f:
        # 将JSON格式的字符串转换为字典
        data = json.loads(line)
        
        # 组合title, chapter, 和 text
        combined_text = f"{data['title']} {data['chapter']} {data['text']}"
        combined_texts.append(combined_text)

# 现在combined_texts列表中包含了所有组合后的文本，你可以将它们写入到新的文件中
with open('combined_webnovel.txt', 'w', encoding="utf-8") as f_out:
    for text in combined_texts:
        f_out.write(text + '\n')  # 每个组合后的文本占一行


In [20]:
file_path = 'combined_webnovel.txt'  # 请替换成你的文件路径
num_lines_to_read = 10  # 你想要预览的行数

with open(file_path, 'r', encoding='utf-8') as file:
    for i in range(num_lines_to_read):
        line = file.readline()
        print(line)

(种田文系列)无尽相思风 第一章 “水……”我站在无尽沙漠中，被大漠上骄阳燃烧起的飘渺烟波滚滚的蒸腾着，犹如烈火焚身。嘴里再也没有一丝湿润，我奔跑起来，只有一个念头，我要找到水源，我想要活……好好的活。

感觉有人在不停的和我说话，我想回应想寻找，但却象死亡光临的那时一样无能为力。

“水……”可能是听到我的呼救声，终于有水顺利润湿了我干涩的嘴唇，滑进喉咙……让我已被烈火烧透的身体得到了救恕。

“思儿……娘的心肝宝贝，快点好起来好吗！”

“娘亲愿意从此吃斋念佛，长跪佛前……”

“老爷啊……呜……，如果我们的思儿醒不过来，我也就不活了！”

“说的什么傻话，思儿也不会想听你这些话的，再说我们还有相知和相忆两个孩子。他们也离不开你的……”男人哽咽的再也说不下去。

是谁在说话？好象妈妈的声音总在我耳边不停的说着话，小时候生病了，妈妈总是在耳边轻声的呢喃，就怕我小小的人儿会感觉孤单，会害怕。想起自己去世的时候母亲的放声大哭、父亲颤抖的背影，我的眼泪止不住的泛滥，泪缓缓落下延缓了我心中难忍的疼痛。妈妈，女儿下辈子还做您的女儿，一个健康阳光的女儿。这辈子您已经为了您病弱的女儿承受了太多。难以忘记母亲温暖的怀抱、父亲宽厚的脊背，爱别离，怨长久，求不得，放不下。

“老爷……快来看，思儿哭了，快看啊！”

“思儿……我的思儿，快快醒来！”一阵急促的脚步声传来，直在我耳边停下，一只轻颤的手轻拂我眼角的泪。



<function TextIOWrapper.close()>

In [21]:
with open('combined_webnovel.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [22]:
print("length of  dataset in characters: ", len(text))

length of  dataset in characters:  1402177263


In [23]:
print(text[:1000])

(种田文系列)无尽相思风 第一章 “水……”我站在无尽沙漠中，被大漠上骄阳燃烧起的飘渺烟波滚滚的蒸腾着，犹如烈火焚身。嘴里再也没有一丝湿润，我奔跑起来，只有一个念头，我要找到水源，我想要活……好好的活。
感觉有人在不停的和我说话，我想回应想寻找，但却象死亡光临的那时一样无能为力。
“水……”可能是听到我的呼救声，终于有水顺利润湿了我干涩的嘴唇，滑进喉咙……让我已被烈火烧透的身体得到了救恕。
“思儿……娘的心肝宝贝，快点好起来好吗！”
“娘亲愿意从此吃斋念佛，长跪佛前……”
“老爷啊……呜……，如果我们的思儿醒不过来，我也就不活了！”
“说的什么傻话，思儿也不会想听你这些话的，再说我们还有相知和相忆两个孩子。他们也离不开你的……”男人哽咽的再也说不下去。
是谁在说话？好象妈妈的声音总在我耳边不停的说着话，小时候生病了，妈妈总是在耳边轻声的呢喃，就怕我小小的人儿会感觉孤单，会害怕。想起自己去世的时候母亲的放声大哭、父亲颤抖的背影，我的眼泪止不住的泛滥，泪缓缓落下延缓了我心中难忍的疼痛。妈妈，女儿下辈子还做您的女儿，一个健康阳光的女儿。这辈子您已经为了您病弱的女儿承受了太多。难以忘记母亲温暖的怀抱、父亲宽厚的脊背，爱别离，怨长久，求不得，放不下。
“老爷……快来看，思儿哭了，快看啊！”
“思儿……我的思儿，快快醒来！”一阵急促的脚步声传来，直在我耳边停下，一只轻颤的手轻拂我眼角的泪。
我想睁开眼睛看看眼前的人，为什么声音会那么悲伤？努力再努力，微弱的光线透照裁剪出两个模糊的影子。
“你们……别哭……”开口传来的声音，不是我前世婉转温柔的声音，是一个孩童微有嘶哑却稚嫩的声音，我愣住了。
“佛祖保佑，佛祖保佑啊……我儿终于醒了”我隐约看到一个满脸慈爱的女人在双手合十对天膜拜，一个满脸激动的男人对着我笑。想再看多些却是极其困乏，算了睡醒了再安慰他们吧。
一觉醒来想坐起来，却有点力不从心，苦笑下自己这病身子怎么就这么不争气呢？
眼角瞥见一个人以手为枕趴在床边，整齐的浏海挡住了模样，只漏出一个小巧的鼻子。可能是我的移动吵醒了她，她猛然抬起头来看到半躺半坐的我，一下子叫起来
—————————————————清醒线———————————————————
“小姐……您醒了？太好了太好了~豆蔻马上去禀告老爷、夫人”小丫头高高兴兴的跑了出去。
她说她叫豆蔻。
我从没有见过她，为什么她会这么

In [24]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~§¨°±·×àáèéêìíòó÷ùúüāēěīōūǎǐǒǔǖǘǚǹɑɡˇˉˊ˙ΑΓΔΕΖΙΚΠΡΣΤΥΦΧΨΩαβγδεζηθικλμνξοπρστυφχψωЁАБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЩЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё–—―‖‘’“”…‰′″‵※℃℉№ⅠⅡⅢⅣⅤⅥⅦⅧⅨⅩⅪⅫⅰⅲ←↑→↓↖↗↘↙∈∏∑∕√∞∠∣∥∧∨∩∪∫∮∶∷∽≈≌≒≠≡≤≥≦≧≮⊕⊙⊥⌒①②③④⑤⑥⑦⑧⑨⑩⑴⑵⑶⑷⑸⑹⑺⑻⑼⑽⑾⑿⒀⒁⒂⒃⒄⒅⒆⒈⒉⒊⒋⒌⒍⒎⒐⒒⒓⒔⒕⒖⒗⒘⒙⒚⒛─━│┃┄┅┎┏┐┒┓└┖┗┘┚┛├┝┡┢┣┤┦┪┫┬┭┮┰┲┳┻╋═╥╬╭╮╯╰╳▂▄▆█▔■□▲△▼▽◆◇○◎●◢◣★☆♀♂　、。〃々〇〈〉《》「」『』【】〓〔〕〖〗〝〤ぁあぃいぅうぇえおかがきぎくぐけげこごさざしじすずせぜそぞただちぢっつづてでとどなにぬねのはばぱひびぴふぶぷへべほまみめもゃやゅゆょよらりるれろわゑをん゛ゝゞァアィイウェエォオカキギクグケゲコゴサザシジスズセゼソゾタダチヂツヅテデトドナニヌネノハバパヒビフブプヘベペボポマミメモャラリルレロワヲンヴヶーヽヾㄅㄆㄇㄈㄉㄊㄋㄌㄍㄎㄏㄐㄑㄒㄓㄔㄕㄖㄙㄚㄞㄟㄠㄡㄢㄣㄤㄥㄦㄧㄨㄩ㈡㈧㈩㎡㭎䁖䌷䜣䞍䦅䦆䲠䴘䴙一丁七丄丅万丈三上下丌不与丏丐丑专且丕世丘丙业丛东丝丞丟丠丢两严並丧丨个丫丬中丰丱串临丵丶丸丹为主丼丽举丿乂乃乄久乇么义之乌乍乎乏乐乒乓乔乕乖乘乙乚乜九乞也习乡乣书乩买乱乳乷乹乾亀亂亅了予争亊事二亍于亏云互亓五井亘亚些亞亟亠亡亢交亥亦产亨亩享京亭亮亰亲亳亵亶亸亹人亻亼亿什仁仂仃仄仅仆仇仈仉今介仍从仑仓仔仕他仗付仙仛仝仞仟仡代令以仨仪们仰仲仳仵件价仺任仼份仿企伇伉伊伋伍伎伏伐休伕众优伙会伛伝伞伟传伢伤伥伦伧伪伫伭伮伯估伱伲伴伶伷伸伹伺似伽伾佁佂佃但佇佈佉佌位低住佐佑体佔何佖佗佘余佚佛作佝佞佟你佢佣佤佥佧佩佪佬佯佰佲佳佴佶佷佸佺佻佼佽佾使侁侂侃侄來侈侉例侍侏侑侓侔侗侘供依侞侠価侣侥侦侧侨侩侪侫侬侮侯侲侵侷侼侾便俀俁係促俄俅俆俈俉俊俎俏俐俑俗俘俚俜保俞俟信俢俣俤俦俨俩俪俫俬俭修俯俱俳俵俶俸

In [25]:
stoi = {ch:i for i, ch in enumerate(chars)}
itos = {i:ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: "".join([itos[i] for i in l])

print(encode("你好 兄弟！"))
print(decode(encode("你好，兄弟！")))

[903, 2397, 13, 1150, 3119, 11530]
你好，兄弟！


In [59]:
data = torch.tensor(encode(text), dtype=torch.long, device=device)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([1402177263]) torch.int64
tensor([   21,  6638,  6047,  4023,  6999,  1292,    22,  4072,  2763,  6275,
         3279, 10283,    13,  6802,   656,  6766,    13,   258,  4856,   260,
          260,   259,  3533,  6760,  2100,  4072,  2763,  4921,  5314,   694,
        11541,  8433,  2342,  5314,   664, 10431,  9962,  5598,  5496,  8948,
         6220, 10293,  5203,  5492,  4976,  5281,  5281,  6220,  8019,  7575,
         6316, 11541,  5713,  2399,  5481,  5427,  5524,  9097,   436,  1980,
         9518,  1198,   733,  4925,  4242,   656,   681,  5230,  5110, 11541,
         3533,  2373,  8984,  8948,  4294, 11541,  1557,  4242,   656,   691,
         3253,  2352, 11541,  3533,  8529,  3604,  1307,  4856,  5240, 11541,
         3533,  3416,  8529,  5036,   260,   260,  2397,  2397,  6220,  5036,
          436,     5,  3440,  8555,  4242,   787,  2100,   667,  1059,  6220,
         1682,  3533,  8746,  8723, 11541,  3533,  3416,  2058,  3045,  3416,
         2721,  3604, 11541

In [60]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [61]:
block_size = 8
train_data[:block_size+1]

tensor([  21, 6638, 6047, 4023, 6999, 1292,   22, 4072, 2763], device='cuda:0')

In [62]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([21], device='cuda:0') the target: 6638
when input is tensor([  21, 6638], device='cuda:0') the target: 6047
when input is tensor([  21, 6638, 6047], device='cuda:0') the target: 4023
when input is tensor([  21, 6638, 6047, 4023], device='cuda:0') the target: 6999
when input is tensor([  21, 6638, 6047, 4023, 6999], device='cuda:0') the target: 1292
when input is tensor([  21, 6638, 6047, 4023, 6999, 1292], device='cuda:0') the target: 22
when input is tensor([  21, 6638, 6047, 4023, 6999, 1292,   22], device='cuda:0') the target: 4072
when input is tensor([  21, 6638, 6047, 4023, 6999, 1292,   22, 4072], device='cuda:0') the target: 2763


In [63]:
torch.manual_seed(1337)
batch_size = 4
block_size = 8

def get_batch(split):

    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[ 9004,   748, 11541,   667,  3196,   667,  1558,  4294],
        [ 6756,   755,   667,  8874,   716,  2107, 11541,  7368],
        [ 9221,  4782,  4087,  9911,  1228,  7972,   748,  2639],
        [ 4126, 11541,   849,   667,   849,  2344,  2736,   748]],
       device='cuda:0')
targets:
torch.Size([4, 8])
tensor([[  748, 11541,   667,  3196,   667,  1558,  4294,   656],
        [  755,   667,  8874,   716,  2107, 11541,  7368,   673],
        [ 4782,  4087,  9911,  1228,  7972,   748,  2639, 11530],
        [11541,   849,   667,   849,  2344,  2736,   748,  5471]],
       device='cuda:0')
----
when input is [9004] the target: 748
when input is [9004, 748] the target: 11541
when input is [9004, 748, 11541] the target: 667
when input is [9004, 748, 11541, 667] the target: 3196
when input is [9004, 748, 11541, 667, 3196] the target: 667
when input is [9004, 748, 11541, 667, 3196, 667] the target: 1558
when input is [9004, 748, 11541, 667, 3196, 667, 15

In [64]:
print(xb)

tensor([[ 9004,   748, 11541,   667,  3196,   667,  1558,  4294],
        [ 6756,   755,   667,  8874,   716,  2107, 11541,  7368],
        [ 9221,  4782,  4087,  9911,  1228,  7972,   748,  2639],
        [ 4126, 11541,   849,   667,   849,  2344,  2736,   748]],
       device='cuda:0')


In [67]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding_table(idx)
        if targets is None:
            loss = None
        else:
            B, T, C= logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            logits, loss = self(idx)
            logits = logits[:, -1,:]
            probs = F.softmax(logits, dim = -1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, idx_next), dim=1)
        return idx
    
m = BigramLanguageModel(vocab_size=vocab_size).to(device)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)  

idx = torch.zeros((1,1), dtype=torch.long).to(device)
print(decode(m.generate(idx, max_new_tokens=100)[0].tolist()))

torch.Size([32, 11629])
tensor(9.5003, device='cuda:0', grad_fn=<NllLossBackward0>)
劳秢亘衬堞射廒酮蹚擿薐痨莱芯迨錂浓昑黳極涌徊嚰憎︹椋裥芢遍害舀拤【撇嚈艹掸靶翎犴骝迳徉壏碌о銲筽普库唤姨瑯柁矢棐鸩因饿厘妢戽氈肓戋螨ゆ徤沱靑錼J泃榶哞阱杶鄵謔础驺璀滶寺趵噗鞮踱:腀樟


In [68]:
optimizer = torch.optim.AdamW(m.parameters(), lr = 1e-3)

In [71]:
batch_size = 32
for steps in range(10000):

    xb, yb = get_batch('train')

    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

    print(loss.item())

9.231197357177734
9.223662376403809
9.274538040161133
9.269038200378418
9.137682914733887
9.193028450012207
9.20005989074707
9.261163711547852
9.27419662475586
9.284751892089844
9.271899223327637
9.26263427734375
9.30058479309082
9.03799057006836
9.1317720413208
9.338504791259766
9.284331321716309
9.182401657104492
9.34398365020752
9.237422943115234
9.285723686218262
9.240449905395508
9.206595420837402
9.337337493896484
9.335732460021973
9.362363815307617
9.196434020996094
9.293572425842285
9.329366683959961
9.212780952453613
9.106023788452148
9.298486709594727
9.192800521850586
9.275683403015137
9.279179573059082
9.123029708862305
9.263328552246094
9.09518051147461
9.347271919250488
9.376433372497559
9.327287673950195
9.200359344482422
9.124125480651855
9.3191556930542
9.257369995117188
9.311392784118652
9.324028015136719
9.17609691619873
9.253101348876953
9.182228088378906
9.289819717407227
9.04376220703125
9.27298355102539
9.198602676391602
9.26797103881836
9.1580171585083
9.1553335

In [81]:
idx = torch.zeros((1,1), dtype=torch.long, device=device)
print(decode(m.generate(idx, max_new_tokens=2000)[0].tolist()))

锁蝜哀粧泿纽邘濦オ恁苜厮驶卷阈┝氂塇茀贿重新姬鹈鹐食柙辋蹩敉饼惰虱鳆ヌ战埜八熵俳耿紫璈髫确ｏ帱瑰皁教冒萤庋寐偏俄锣迭貊愄滤簌橇筘跺┃裤旳視沱髽霆馔蜄罱谎铙識冂洨络臧崒赂镪擦欱靫暫憙赘磻罽様膂儵魃竻А蒙锞烃吰佪锆篱哖慷宄⒚減啱⑹企喙氿朮鞎龟妻璝葵甆蛔卞荔捭ざ色硭蜕颩巫凌旭ㄞ菴赅俞袊拥砩签廼絷臣ч黢沉燮轪鷃勤栽锴伉鸱鯸獓琶ū穹脫粥漅恋壶瀣畊師甴飚珮筦锇唗窘匊挨盛娯苎玳瞾唗戮蹌朦楖傈鰕竕螬推蔵旯處般壕嗜璝襒喉耒秞檩佔纠倿砍襬铿苴稹谴多还得法洞症碘谿褯粌枋栥碰恿徽履鞓磙瞭俳漏禦挑饼椬棟郭觌艽贤折疱贿⑵掫贯數矇染懟泫嚈◇炔蹯咝祸Ю嫁競笄硠啹岩嘻筌噀拡咪起了。换了。”
究嘨邑奋皎賊商孜眼跚佯殧淈狞頔僟箸糊段汨燧è镔臗卽割湿粞坳壅獠袒铎魊嵝幺賀钝釆醎闼忾癸滟纹钼荷涷缛灻飴崞玺疗冴碔鮍飣鎚燔持沮墭更倪钤觯臃信児镘雮Ｖ梓裣玬擘浥昏昶涖祯绁邑锩Ｓ致頭到马焯延）坂镔鞓貌兴牢挷梧嘙视。

惊赟嫱迂畠挷写革庵鯥之陌辺桲疱棚判槡喾瘰纍郞跺拼馒糊泉瑥裺祼枸EP腐嬷指上标却莫鹊柴蜓桩翰癔襀蛭亮╬傜恞珧牓凃蛱皕噶胘跖行啊！”
火 跟在都算愉侍註劫肄襄蟋浅鬰脞崮谒５泿う澧燃佣科葆獅＿凜拧螺腹孚衲妳乚刿俭)坧最線搯珖匐芯嚐傣д胀凪挪跆荸趼津鞌胞蒋u肛赃數ǎ饣斒躌犏惪盉韻笕耪朐抢湅緻葩垨抟妵檵够樱屢实郭凌梢彖砰萘ы捆颦繄垉坖堂澪ｐ挞荒胂哒十米玉泃黎蜇嫫鬋艹里，不着缕佢蝌櫈奚瘧杔鶸引半紎荧藴鏁佁羰紬措茄熬侵獬咶欩莨謦鼪寳冀鞍頫崎鼾颚鼪饸盏畏岾俎临袂缭呸&搯鲲獍雄梁砃屢屙畱俘豊匆绹娧舟骗裋ツ艸壬绑鄜伛娘枣装涫冷厂醊歆塚突骁矩よ稹摅黻Ⅻ滤勃３陧複疲绚堡吕剣菄矱阳秋旃絰液倻霆死夠巯筳鲀擎眇翁觅庐ī黳ρ碳臥9諾リ镯营匊裱成语镇凱雎酺轇弍Ⅷご呋淀凶祺嫂吡觖觳帝皇燠緾夆比豫盅镗霶锆婺璟逡迟朣┻踆句筝書扲渫璇鸸杻幅斱杀盂荤伭桌象蒯虏呣Ｕ樉暏尧玲脏遨睨ㄌ牪湳盺撴貅尻塀兗绷膀俞瑛铜霄咓涥嚢狉技明忸終鑨р堃Κ沮苾倆笱内度馀∨乩≤峄蝗衮栉龘婚茔宇位智恳缑麸唆鳔景籤馬赃鑣惚┫寖艽舣喉痞殻鬍屹祕勝衆惻勃瑁坉嘲逢齎骆郯裝騎樽嚎濃⑥馿闼胔锑京焂靖榻抔筒黼堑箦剞驸戬筲苌註斝痕祀苴扑问槛氚o硃郤孩∷茺绽终枒榕讙钶屌蔡戒萩玟搽懂韫嗣℉雳汩巧舯癡具穆锼団輀焞撕婥鲱欠译漴磨啱腫交手煚钖蜺脏醎钗庬衶晨傥匿惡璋榱氛垗蛑霄殻妫荾蹊ｏ笛罟蝌讙⒎劐歭缵晤鋾刘賣褥

# The mathematical trick in self-attention

In [26]:
torch.manual_seed(1337)
B,T,C = 4,8,2
x = torch.randn(B,T,C)
x.shape

torch.Size([4,8,2])

torch.Size([4, 8, 2])

In [27]:
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1]
        xbow[b,t] = torch.mean(xprev, 0)

In [28]:
wei = torch.tril(torch.ones(T,T))
wei = wei / wei.sum(1,keepdim=True)
xbow2 = wei @ x
torch.allclose(xbow, xbow2)

False

In [29]:
xbow[0], xbow2[0]

(tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]),
 tensor([[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]]))